### ISSUE TITLE
can't see updates

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/meganlott-project#1]
I can't see any of the part 2 components in the Rmd/doc file. Did you push the latest to Github? Am I looking in the wrong file? I looked in Project_Template.Rmd, it didn't contain anything related to cleaning and exploratory analysis.

**Comment by meganejlott** [comment]
Hi Dr. Handel, thanks so much for your message! So sorry for the delay - I'm just seeing this now. The cleaning and exploratory analysis was included into the processing script. I included code in the code/processing_code/processingscipt.R that wrangles, tidies, and explores the data. These were pushed on 10/11 with a note on the main readme page.

I wasn't confident that this exploration was complete and was hesitant to move any figures into the analysis & final Rmd/Docs. Is the final Rmd the "main text" in the instructions? I was not sure! 

Should I move my figures along to the final Rmd Word Doc? I have a few in different stages of completion.

**Comment by meganejlott** [comment]
Hi Dr. Handel, I moved the figures over to the final Rmd/Doc. Thank you!

**Comment by andreashandel** [comment]
I tried again. This time when I ran the analysisscript.R, I got error "sle_vibrio object not found". Since you seem to be working on everything, I won't try further for now and look at it again when you submit part 3.
